export const ServicesName = {
	node: "node",
	mongodb: "mongodb",
	mongoexpress: "mongo-express",
	redis: "redis",
	redisinsight: "redisinsight",
	mysql: "mysql",
	phpmyadmin: "phpmyadmin",
	postgresql: "postgresql",
	pgadmin: "pgadmin",
	rabbitmq: "rabbitmq",
	elasticsearch: "elasticsearch",
	kibana: "kibana",
	kafka: "kafka",
	nginx: "nginx",
};
